#!/bin/bash
READLINK=readlink
which greadlink && READLINK=greadlink

pluginpath="$(dirname "$($READLINK -f $0)")"
ln -svf $pluginpath/vimrc "$HOME/.vimrc"
rm -rvf "$HOME/.vim"
ln -sv $pluginpath "$HOME/.vim"

pushd $pluginpath/bundle/LanguageClient-neovim
bash install.sh
popd

which npm && npm install -g typescript-language-server
which go && go install github.com/juliosueiras/terraform-lsp
